wanpipe-3.3.2.tgz

diff --git a/ssmg/sangoma_mgd.trunk/install b/ssmg/sangoma_mgd.trunk/install
--- a/ssmg/sangoma_mgd.trunk/install
+++ b/ssmg/sangoma_mgd.trunk/install
@@ -1,13 +1,51 @@
 #!/bin/sh
 
+# ----------------------------------------------------------------------------
+# Prompt user for input.
+# ----------------------------------------------------------------------------
+prompt()
+{
+	if test $NONINTERACTIVE; then
+		return 0
+	fi
+
+	echo -ne "$*" >&2
+	read CMD rest
+	return 0
+}
+
+# ----------------------------------------------------------------------------
+# Get Yes/No
+# ----------------------------------------------------------------------------
+getyn()
+{
+	if test $NONINTERACTIVE; then
+		return 0
+	fi
+
+	while prompt "$* (y/n) "
+	do	case $CMD in
+			[yY])	return 0
+				;;
+			[nN])	return 1
+				;;
+			*)	echo -e "\nPlease answer y or n" >&2
+				;;
+		esac
+	done
+}
+
+
+
 home=`pwd`;
 
 force="false"
-noss7="false"
+noss7="true"
 rootdir=""
 pbxdir=/usr/src/asterisk
 pbxd="asterisk"
 cfgdir="/etc/asterisk"
+mysyslog=" "
 
 
 
@@ -78,34 +116,80 @@ if [ $force = "force" ]; then
 	echo
 else 
 	if [ -f /var/run/sangoma_mgd.pid ]; then
-		echo "Error: sangoma_mgd is running!"
-		exit 1
+		echo "Warning: sangoma_mgd is running!"
+		getyn "Would you like to stop sangoma_mgd?"
+		if [ $? -ne 0 ]; then
+			exit 1
+		fi
+		
+		eval "sangoma_mgd -term"
+		if [ -f /var/run/sangoma_mgd.pid ];then
+			echo "Failed to stop sangoma_mgd"
+			exit 1
+		fi
 	fi
 	if [ -f /var/run/asterisk.pid ]; then
-		echo "Error: asterisk is running"
-		exit 1
+		echo "Warning: asterisk is running"
+		getyn "Would you like to stop asterisk?"
+		if [ $? -ne 0 ]; then
+			exit 1
+		fi
+		eval "asterisk -rx \"stop now\" >/dev/null 2>/dev/null"
+		sleep 2
+		if [ -f /var/run/asterisk.pid ]; then
+       			kill -TERM $(pidof asterisk);
+			sleep 2
+			if [ -f /var/run/asterisk.pid ]; then
+				echo "Failed to stop asterisk"
+				exit 1
+			fi
+		fi
 	fi
 fi
 
 echo
 echo "Checking Syslog ...."
 if [ -e  /etc/syslog.conf ]; then
-eval "grep "local2.*sangoma_mgd" /etc/syslog.conf" > /dev/null 2> /dev/null
-if [ $? -ne 0 ]; then
-	eval "grep "local2" /etc/syslog.conf " > /dev/null 2> /dev/null
-	if [ $? -eq 0 ]; then
-		echo
-		echo "Warning : local2 is already used in syslog.conf"
-		echo
-	fi
-	echo -e "\nlocal2.*                /var/log/sangoma_mgd.log\n" > tmp.$$
-	eval "cat /etc/syslog.conf tmp.$$ > tmp1.$$"
-	\cp -f tmp1.$$ /etc/syslog.conf
-	eval "/etc/init.d/syslog restart"
+        echo "found /etc/syslog.conf "
+        mysyslog=syslog
+elif [ -e /etc/rsyslog.conf ] ; then
+        echo " found /etc/rsyslog.conf "
+        mysyslog='rsyslog'
+else
+               echo " Warning : Syslog not found "
+               mysyslog=" "
 fi
 
-else
-	echo "Warning: /etc/syslog.conf not found"
+
+if [  $mysyslog != " " ]; then
+	eval "grep "local2.*sangoma_mgd" /etc/$mysyslog.conf" > /dev/null 2> /dev/null
+	if [ $? -ne 0 ]; then
+		eval "grep "local2" /etc/$mysyslog.conf " > /dev/null 2> /dev/null
+		if [ $? -eq 0 ]; then
+			echo
+			echo "Warning : local2 is already used in $mysyslog.conf"
+			echo
+		fi
+		echo -e "\n# Sangoma Media Gateway log" > tmp.$$
+		echo -e "local2.*                /var/log/sangoma_mgd.log\n" >> tmp.$$
+		eval "cat /etc/$mysyslog.conf tmp.$$ > tmp1.$$"
+		\cp -f tmp1.$$ /etc/$mysyslog.conf
+		eval "/etc/init.d/$mysyslog restart"
+	fi
+	eval "grep "local3.*sangoma_bri" /etc/$mysyslog.conf" > /dev/null 2> /dev/null
+        if [ $? -ne 0 ]; then
+                eval "grep "local3" /etc/$mysyslog.conf " > /dev/null 2> /dev/null
+                if [ $? -eq 0 ]; then
+                        echo
+                        echo "Warning : local3 is already used in $mysyslog.conf"
+                        echo
+                fi
+		echo -e "\n# Sangoma BRI Daemon (smg_bri)  log" > tmp.$$
+                echo -e "local3.*                /var/log/sangoma_bri.log\n" >> tmp.$$
+                eval "cat /etc/$mysyslog.conf tmp.$$ > tmp1.$$"
+                \cp -f tmp1.$$ /etc/$mysyslog.conf
+                eval "/etc/init.d/$mysyslog restart"
+        fi
 fi
 
 if [ -f tmp1.$$ ]; then
@@ -117,7 +201,6 @@ fi
 
 echo "Ok"
 echo
-
 echo "Checking logrotate ..."
 eval "type logrotate" > /dev/null 2> /dev/null
 if [ $? -ne 0 ]; then
@@ -143,27 +226,13 @@ if [ -e /etc/logrotate.d ] && [ -e /etc/logrotate.d/syslog ]; then
 else
         echo "Error: Logrotate dir: /etc/logrotate.d not found !"
 fi
+
 echo "OK."
 echo
-
 echo "Checking for SCTP Utilities...."
-if [ ! -e  /usr/include/netinet/sctp.h ]; then
-	if [ -d ../libs ]; then
-		echo -n "Installing SCTP RPMS ..."
-		eval "rpm -i ../libs/lksctp-tools-1.0.6-1.el5.1.i386.rpm  ../libs/lksctp-tools-devel-1.0.6-1.el5.1.i386.rpm"
-		if [ ! -e  /usr/include/netinet/sctp.h ]; then
-			echo "Error"
-			echo
-			echo "Please install SCTP devel package: yum install lksctp-tools-devel"
-			echo 
-			exit 1
-		fi 
-		echo "OK"
-	else 
-		echo "Please install SCTP devel package: yum install lksctp-tools-devel"
-		echo 
-		exit 1
-	fi
+if [ ! -e  /usr/include/netinet/sctp.h ] && [ ! -e /usr/include/sctp.h ]; then
+	echo "Error: lksctp-tools-devel package missing"
+	exit 1
 fi 
 echo "OK."
 echo
@@ -190,7 +259,12 @@ eval "make"
 if [ $? -ne 0 ]; then
 	exit 1;
 fi
-make INSTALLPREFIX=$rootdir install
+
+if [ $noss7 == 'true' ]; then
+	make INSTALLPREFIX=$rootdir NO_SS7=YES install
+else
+	make INSTALLPREFIX=$rootdir install
+fi
 echo "Ok."
 
 if [ -d chan_woomera.trunk ]; then
