wanpipe-2.3.4-16.tgz

diff --git a/diff b/diff
--- a/diff
+++ b/diff
@@ -1,292 +1,180 @@
---- /root/3.1.X/wanpipe/Setup	2007-07-19 15:49:43.000000000 -0400
-+++ Setup	2007-07-19 18:31:53.000000000 -0400
-@@ -1593,6 +1593,7 @@
- 	echo "WAN_LIB_DIR=/etc/wanpipe/lib" >> $META_CONF
- 	echo "WAN_ADSL_LIST=/etc/wanpipe/wan_adsl.list" >> $META_CONF
- 	echo "WAN_ANNEXG_LOAD=$ANNEXG_LOAD" >> $META_CONF
-+	echo "WAN_SCTP_LOAD=$SCTP_LOAD" >> $META_CONF
- 	echo "WAN_LIP_LOAD=$LIP_LOAD" >> $META_CONF
- 	echo "WAN_DYN_WANCONFIG=NO" >> $META_CONF
- 	echo "WAN_SCRIPTS_DIR=/etc/wanpipe/scripts" >> $META_CONF
-@@ -1814,14 +1815,14 @@
- 	1) create WANPIPE configuration files.
- 		(/usr/sbin/wancfg)
- 	2) create configuration files for Zaptel and Asterisk
--		(/usr/sbin/wancfg-zaptel)
--	2) start,stop,restart individual/all devices and interfaces.
-+		(/usr/sbin/wancfg_zaptel)
-+	3) start,stop,restart individual/all devices and interfaces.
- 		(/usr/sbin/wanrouter)
--	3) debug line, protocol and driver problems.
-+	4) debug line, protocol and driver problems.
- 		(/usr/sbin/wanpipemon)
--	4) configure the optional onboard FT1 CSU/DSU (S508/S5143).
-+	5) configure the optional onboard FT1 CSU/DSU (S508/S5143).
- 		(/usr/sbin/cfgft1)
--	5) aid in WANPIPE API development
-+	6) aid in WANPIPE API development
- 		(/etc/wanpipe/api)
+--- Setup	2007-10-29 16:38:54.000000000 -0400
++++ /root/3.2/wanpipe/Setup	2007-10-29 16:34:04.000000000 -0400
+@@ -9,6 +9,7 @@
+ #		as published by the Free Software Foundation; either version
+ #		2 of the License, or (at your option) any later version.
+ # ----------------------------------------------------------------------------
++# Oct 26, 2007  Konrad Hammel   Updated minor start script bug
+ # Nov 27, 2005  David Rokhvarg 	Added Echo Debugging option
+ # Mar 18, 2002  Nenad Corbic	Added BSCSTRM protocol
+ # Mar 01, 2002  Nenad Corbic	Added option to split rpm build into
+@@ -1642,8 +1643,8 @@
+ 		getyn "Would you like to auto-execute ztcfg after wanrouter start?" || return 0
+ 			if [ ! -d $WAN_CONF_DIR/scripts ]; then
+ 				eval "\mkdir -p $WAN_CONF_DIR/scripts >/dev/null 2>/dev/null"
+-			fi 
+-			eval "\cp -f  $PROD_HOME/samples/wanpipe_zaptel_start $WAN_CONF_DIR/scripts/start >/dev/null 2>/dev/null"
++			fi
++			eval "\cp -f  $PROD_HOME/samples/wanpipe_zaptel_start $WAN_CONF_DIR/scripts/start > /dev/null 2> /dev/null"
+ 			if [ ! -f $WAN_CONF_DIR/scripts/start ]; then
+ 				echo "Error: Could not copy auto-ztcfg script"
+ 			fi
+@@ -2502,7 +2503,7 @@
+        Default for: Asterisk SS7 + PRI
  
- Refer to the WanpipeInstallation.(pdf/txt) for more information.
-@@ -3202,6 +3203,7 @@
- 		CONFIG_SMP=NO;
+ 6. TDM API  
+-       Protocols: TDM API, Q921 on AFT adapters:
++       Protocols: TDM API on AFT adapters:
+        Default for: FreeSwitch, Yate, Sunrise
+                     Custom voice development 
+ 
+@@ -2546,7 +2547,6 @@
+ 
+ 	elif [ "$response"  -eq 6 ]; then
+                 enable_protocols "AFT_TE1"
+-                enable_protocols "LIPAPI"
+ 
+ 	elif [ "$response"  -eq 7 ]; then
+ 		enable_custom_protocols 
+@@ -4979,6 +4979,21 @@
+                 fi
+         fi
+ 
++        eval "cat Makefile |sed 's/^SUBDIR_MODULES:=.*//g'>$TEMP 2>/dev/null "
++        if [ $? -ne 0 ]; then
++                echo "   Failed to remove wct4xxp from Makefile"
++                exit 1
++        else
++                eval "\mv -f $TEMP Makefile"
++                if [ $? -ne 0 ]; then
++                        echo "   Failed to overwrite existing Makefile"
++                        exit 1
++                else
++                        echo "   wct4xxp module removed from Makefile successfully"
++                        zaptel_modified=1
++                fi
++        fi
++
+ 	if [ -f Makefile.kernel26 ]; then
+ 		eval "cat Makefile.kernel26 | sed 's/^obj-m.*+=.*wct4xx.*//g'>$TEMP 2>/dev/null "
+ 		if [ $? -ne 0 ]; then
+@@ -5357,10 +5372,10 @@
+ 	local zapdir_manual=0
+ 	local zapdirs=$1
+ 
++	echo
++	echo "Looking for zaptel directory in /usr/src ..."	
++	echo "-------------------------------------------"
+ 	if [ "$zapdirs" = "" ]; then
+-		echo
+-		echo "Looking for zaptel directory in /usr/src ..."	
+-		echo "-------------------------------------------"
+ 		zapdirs=`find /usr/src -maxdepth 2 -name 'zaptel*' | xargs `
  	fi
  
+@@ -5419,7 +5434,12 @@
+ #	echo "d4: Download Latest 1.4"
+ 	echo "(ctrl-c to Exit)"
+ 	echo -n "Please select working zaptel directory [1-9][m]: "
 +
- 	#Find out our processor type. This is needed to properly
- 	#compile our modules.
- 	echo -n "Checking current processor type ..."
-@@ -3301,6 +3303,10 @@
- 			fi
- 		fi
++	response=1
++
++	if [ -z $NONINTERACTIVE ] || [ $zaptel_auto_install = "YES" ]; then
+ 	read response
++	fi
  
-+		
-+
-+
-+
- 		echo -n "Compiling General ${DISTR_NAME} Driver for 2.6.X Kernel ."
+ 	if [ "$response" = "" ]; then
+ 		find_zap_dirs_invalid "$zapdirs"
+@@ -5830,6 +5850,7 @@
+ 
+ 				exit 1
+ 			else
++				echo
  		
- 	
-@@ -3485,18 +3491,6 @@
- EVALCMD=eval
- WANPIPE_OBJS=
+ 				if [ $TDM_PROT != YES ]; then
+ 					echo "Enabling the TDM Voice Asterisk Support"
+@@ -5838,6 +5859,15 @@
+ 					WANCFG_ZAPTEL_CFG=YES
+ 				fi
  
--
-- 		 if [ 0 -eq 1 ]; then
--                echo
--                echo "ALLFLAGS"
--                echo "--------------------------------------------------"
--                echo "$CFLAGS"
--                echo "--------------------------------------------------"
--                echo
--                echo
--		fi
--                      
--
- 	rm -f sdladrv_src.c
- 	ln -s sdladrv.c sdladrv_src.c
- 	build_kernel_module sdladrv "sdladrv_src sdladrv_fe"
-@@ -3763,8 +3757,10 @@
- 		\cp -f $DRIVER_UPDATE_DIR/src/lip/*.c  .
- 		\cp -f $DRIVER_UPDATE_DIR/src/lip/bin/*.o .
- 
--		\cp -f $DRIVER_UPDATE_DIR/src/lip/lip_katm/*.c .
--		\cp -f $DRIVER_UPDATE_DIR/src/lip/lip_katm/*.h .
-+		if [ -e $DRIVER_UPDATE_DIR/src/lip/lip_katm ]; then 
-+			\cp -f $DRIVER_UPDATE_DIR/src/lip/lip_katm/*.c .
-+			\cp -f $DRIVER_UPDATE_DIR/src/lip/lip_katm/*.h .
-+		fi
- 
- 		LIP_LINKED_PROTOCOLS=
- 
-@@ -3872,6 +3868,9 @@
- 		fi
- 
- 		if [ $XMTP2_PROT = "YES" ]; then
 +
-+			SCTP_LOAD=YES
++				eval "grep ZT_DCHAN_TX_V2 $ZAPTEL_INSTALL_DIR/* 2> /dev/null > /dev/null"
++				if [ $? -eq 0 ]; then
++					TDM_DCHAN="(DCHAN)"
++					PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DCONFIG_PRODUCT_WANPIPE_TDM_VOICE_DCHAN"
++					echo "Sangoma DCHAN Patch detected in zaptel"
++				fi
 +
- 			xmtp2_file=wanpipe_xmtp2.gcc$GCC_VER.$ARCH$REGPARM_OPT.o
- 			if [ ! -e $xmtp2_file ]; then
- 				echo "Warning: FR Binary $xmtp2_file not found!"
-@@ -4390,34 +4389,39 @@
-         eval "ldconfig"
- 
- 	cd $PROD_HOME/$SSMG_DIR
--	cd sangoma_mgd.trunk
- 
--        eval "make clean > /dev/null; make > /dev/null "
--        if [ $? -ne 0 ]; then
--	  	echo "FAILED"
--		return 1
--	fi
--        eval "make install > /dev/null "
--	
--	echo "Installing Sangoma Media Gateway Daemon...DONE"
-+#	Let smg install script install SMG components
-+#=======================================================
 +
-+#	cd sangoma_mgd.trunk
-+#
-+#       eval "make clean > /dev/null; make > /dev/null "
-+#        if [ $? -ne 0 ]; then
-+#	  	echo "FAILED"
-+#		return 1
-+#	fi
-+#        eval "make install > /dev/null "
-+#	
-+#	echo "Installing Sangoma Media Gateway Daemon...DONE"
- 	
--       	eval "type asterisk > /dev/null 2> /dev/null"
--	if [ $? -ne 0 ]; then
--          	echo "Error: Asterisk not installed!"
--		echo "Please install Asterisk first then retry SSMG installation!"
--		return 1
--	fi  	
-+#      	eval "type asterisk > /dev/null 2> /dev/null"
-+#	if [ $? -ne 0 ]; then
-+#          	echo "Error: Asterisk not installed!"
-+#		echo "Please install Asterisk first then retry SSMG installation!"
-+#		return 1
-+#	fi  	
-  	
--	echo
--	echo "Installing Chan Woomera into Asterisk..."
--	echo
--	install_chan_woomera
--	if [ $? -ne 0 ]; then
--          	echo "Error: Failed to install chan_woomera into Asterisk!"
--		echo "Check that Asterisk is installed or Call Sangoma Tech Support"
--		echo
--		return 1
--	fi	
-+#	echo
-+#	echo "Installing Chan Woomera into Asterisk..."
-+#	echo
-+#	install_chan_woomera
-+#	if [ $? -ne 0 ]; then
-+#         	echo "Error: Failed to install chan_woomera into Asterisk!"
-+#		echo "Check that Asterisk is installed or Call Sangoma Tech Support"
-+#		echo
-+#		return 1
-+#	fi	
-+#=========================================================
- 
- 	cd $PROD_HOME/$SSMG_DIR
- 	cd sangoma_mgd.trunk 
-@@ -4868,62 +4872,6 @@
-         return 0;
- }
- 
--function tdmv_apply_zaptel_dchan_patch ()
--{
--	lhome=`pwd`
--
--	cd $ZAPTEL_INSTALL_DIR
--
--	eval "grep \"DCHAN_TX\" $ZAPTEL_C_FILE > /dev/null 2> /dev/null"
--	if [ $? -eq 0 ]; then
--
--		eval "grep \"ZT_DCHAN_TX_V2\" $ZAPTEL_C_FILE > /dev/null 2> /dev/null"
--		if [ $? -eq 0 ]; then
--			echo "   Zaptel DCHAN patch V.02 already installed"
--			cd $lhome
--			return 1
--		else
--			echo "   ERROR: Old Zaptel DCHAN patch detected in $ZAPTEL_INSTALL_DIR"
--			echo
--			echo "       Please install a fresh version of Zaptel source and"
--			echo "       run ./Setup again."
--			echo 
--			cd $lhome
--			exit 1
--		fi
--	fi
--
--	# patch zaptel.h
--	eval "search_and_replace zaptel.h zaptel.h \"$ZAPTEL_H_SEARCH_STR\" \"$ZAPTEL_H_PATCH\""
--
--	if [ $? -ne 0 ]; then
--		echo "search_and_replace(zaptel.h) failed"
--		cd $lhome
--		return 2
--	#else
--	#	echo "search_and_replace($ZAPTEL_C_FILE) succeeded"
--	fi
--
--	# patch $ZAPTEL_C_FILE
--        eval "grep \"$ZAPTEL_C_SEARCH_STR\"  $ZAPTEL_C_FILE > /dev/null 2> /dev/null"
--	if [ $? -eq 0 ]; then
--		eval "search_and_replace $ZAPTEL_C_FILE $ZAPTEL_C_FILE \"$ZAPTEL_C_SEARCH_STR\" \"$ZAPTEL_C_PATCH\""
--	else
--		eval "search_and_replace $ZAPTEL_C_FILE $ZAPTEL_C_FILE \"$ZAPTEL_C_SEARCH_STR_NEW\" \"$ZAPTEL_C_PATCH_NEW\""
--	fi
--
--	if [ $? -ne 0 ]; then
--		echo "search_and_replace($ZAPTEL_C_FILE) failed"
--		cd $lhome
--		return 2
--	else
--		#echo "search_and_replace($ZAPTEL_C_FILE) succeeded"
--		cd $lhome
--		zaptel_modified=1
--		return 0
--	fi
--}
--
- function tdmv_apply_zaptel_dchan_patch_old ()
- {
- 	local rc
-@@ -5761,13 +5709,15 @@
- 
- 				PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DCONFIG_PRODUCT_WANPIPE_TDM_VOICE_DCHAN"
+ 				if [ "$TDM_DCHAN" = "" ]; then
+ 				echo 
  				echo
--				tdmv_apply_zaptel_dchan_patch
--				if [ $? -eq 0 ]; then
-+			#	tdmv_apply_zaptel_dchan_patch
-+				eval "$PROD_HOME/patches/sangoma-zaptel-patch.sh $ZAPTEL_INSTALL_DIR"
-+				result=$?
-+				if [ $result -eq 0 ]; then
-                                         TDM_DCHAN="(DCHAN)"
-                                         echo "   Zaptel DCHAN Patch successful"
-                               #          getyn "Confirm Zaptel Patching: yes/no to continue!"
-                                         echo
--                                elif [ $? -eq 1 ]; then
-+                                elif [ $result -eq 1 ]; then
-                                         TDM_DCHAN="(DCHAN)"
-                                         echo
-                                 else
-@@ -6177,7 +6127,7 @@
+@@ -5932,6 +5962,7 @@
+ 				TDM_PROT=YES
+ 				zaptel_modified=1;
+ 				if [ $zaptel_modified ] && [ $zaptel_modified -eq 1 ] && [ "$ZAPTEL_COMPILE_DISABLE" = "NO" ]; then
++					echo
+ 					getyn "Recompile/reinstall Zaptel (recommended) ?"
+ 					if [ $? -eq 0 ]; then
+ 						tdmv_compile_zaptel
+@@ -6266,11 +6297,11 @@
  PKG_NAME=wanpipe
  DISTR_NAME="WANPIPE"
  PROD=wanrouter
--PROD_VER=3.1.2
-+PROD_VER=2.3.4-12.p1
+-PROD_VER=2.3.4-15
++PROD_VER=3.2.1
  PROD_HOME=`pwd`
- META_CONF=$PROD_HOME/$PROD.rc
+-META_CONF=$PROD_HOME/$PROD.rc
++WAN_CONF_DIR=/etc/wanpipe            
++META_CONF=$WAN_CONF_DIR/$PROD.rc      
  WAN_INTR_DIR=$PROD_HOME/interfaces
-@@ -6256,6 +6206,7 @@
- SS7_USER_ID="0"
+-WAN_CONF_DIR=$PROD_HOME
+ PROD_CONF=$WAN_CONF_DIR/wanpipe1.conf
+ PROD_PATCH=$PROD_HOME/patches
+ PROD_INIT=/usr/sbin/
+@@ -6521,6 +6552,9 @@
+ 	EXTRA_ARGS=" --protocol=TDM --silent "
+ fi
  
- ANNEXG_LOAD=NO
-+SCTP_LOAD=NO
++if [ "$setup_cmd" = "buildrpm" ]; then
++	EXTRA_ARGS=" --no-zaptel-compile "
++fi
  
- ZAPTEL_INSTALL_DIR="/usr/src/zaptel"
- ZAPTEL_C_FILE="zaptel.c"
-@@ -6447,6 +6398,7 @@
- 		--no-gcc-debug*)
- 			DISABLE_GCC_DEBUG=1;
- 			;;
-+			
- 		--usr-cc*)
- 			USR_CC=`echo $arg | cut -d'=' -f2`;
- 			eval "type $USR_CC";
-@@ -6477,9 +6429,15 @@
- 		--noautostart*)
- 			NO_AUTO_START=1
- 			;;
-+		
-+		--ignore-t1-yellow*)
-+			PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DWANPIPE_IGNORE_T1_YELLOW " 
-+			;;
-+
- 		--64bit_4G*)
+ if [ "$PKG_NAME" != "wanpipe-lite" ]; then
+          
+@@ -6590,6 +6624,10 @@
  			PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DWANPIPE_64BIT_4G_DMA "
  			;;
+ 
++		--hwec_noise_reduction*)
++			PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DWANEC_ENABLE_NOISE_REDUCTION "
++			;;
 +
  		--with-linux*)
  			SOURCEDIR=`echo $arg | cut -d'=' -f2`;
  			if [ "$SOURCEDIR" = "" ]; then
-@@ -6612,10 +6570,10 @@
- 		--gz-modules)
- 			GZ_MODULES="YES";
- 			;;
----zap-chunk*)
-+		--zap-chunk*)
-                         ZAP_CHUNK=`echo $arg | cut -d'=' -f2`;
+@@ -6856,9 +6894,13 @@
+ 	5. Wan Protocols     : $PROTS
+ 	
+ 	6. Build Directory   : $PROD_HOME/$build_dir 
+-
+ "
  
--                        if [ $ZAP_CHUNK != "8" ] && [ $ZAP_CHUNK != "16" ] && [ $ZAP_CHUNK != "40" ] && [ $ZAP_CHUNK != "80" ];  then
-+                         if [ $ZAP_CHUNK != "8" ] && [ $ZAP_CHUNK != "16" ] && [ $ZAP_CHUNK != "40" ] && [ $ZAP_CHUNK != "80" ];  then
-                                 echo "Error: Invalid Zaptel Chunk size"
-                                 exit 1;
-                         else
++	if [ $TDM_PROT = "YES"  ]; then
++echo "	7. Zaptel Build Dir  : $ZAPTEL_INSTALL_DIR "
++	fi
++	echo
++	echo
+ 		if [ $KERNEL_UNAME != $KERNEL_VERSION ]; then
+ 
+ 			echo "
+@@ -7059,8 +7101,8 @@
+ prepare	|| exit 1
+ apply_patches || exit 1
+ compile_drivers  || exit 1
++install_config || exit 1   
+ install_init || exit 1
+-install_config || exit 1
+ compile_src || exit 1
+ install_all 
+ install_ssmg
