wanpipe-3.5.24.tgz

diff --git a/Setup b/Setup
--- a/Setup
+++ b/Setup
@@ -1540,7 +1540,7 @@ create_mataconf()
 	fi
 
 	cat > $META_CONF << ENDOFTEXT
-#!/bin/sh
+#!/bin/bash
 # router.rc	WAN router meta-configuration file.
 #
 #		This file defines variables used by the router shell scripts
@@ -1952,7 +1952,27 @@ WARNING: The Linux source in $SOURCEDIR has not been configured.
 		pause
 	fi
 	eval "make install DESTDIR=$ROOT >> $CMP_LOG 2>> $CMP_LOG"
+	
+	echo -n "Compiling WANPIPE LibStelephony API library ..."
+	
 	cd ..
+	cd libstelephony
+	eval "./init-automake.sh  >> $CMP_LOG 2>> $CMP_LOG"
+	eval "./configure --prefix=/usr >> $CMP_LOG 2>> $CMP_LOG" 
+	eval "make clean >> $CMP_LOG 2>> $CMP_LOG" 
+	eval "make CC=$CC DESTDIR=$ROOT >> $CMP_LOG 2>> $CMP_LOG" 
+	if [ $? -eq 0 ]; then
+		echo -e "Done.\n\n"
+	else
+		echo -e "Failed. \n\n"
+		pause
+	fi
+	eval "make install DESTDIR=$ROOT >> $CMP_LOG 2>> $CMP_LOG"
+	cd ..
+
+	if [ $superuser = "YES" ] && [ -z $ROOT ]; then
+        	eval "ldconfig"
+	fi
 
 	cd $PROD_HOME/util
 
@@ -3684,7 +3704,7 @@ CFLAGS="$CC -Wp,-MD,.wanpipe.o.d -nostdinc -iwithprefix include -D__LINUX__ -Dli
 
 cat <<ENDOFTEXT > $PROD_HOME/scripts/Compile_Setup.sh
 
-#!/bin/sh
+#!/bin/bash
 
 if [ -e kdrvcmp ]; then
 	rm -rf kdrvcmp
@@ -3718,7 +3738,7 @@ ENDOFTEXT
 tmp=${CFLAGS/$CC/}
 cat <<ENDOFTEXT > $PROD_HOME/scripts/Compile.sh
 
-#!/bin/sh
+#!/bin/bash
 
 make CFLAGS="$tmp"  PROTOCOL_DEFINES="$PROTOCOL_DEFINES"
 
@@ -4464,7 +4484,7 @@ WANPIPE_OBJS=
 
 
 	   cat <<ENDOFTEXT > $CMP_INSTALL
-#!/bin/sh
+#!/bin/bash
 
 	   mv *.ko mod/ > /dev/null 2> /dev/null
 
@@ -4509,7 +4529,7 @@ ENDOFTEXT
 	   chmod 755 $CMP_INSTALL
 
 	 cat <<ENDOFTEXT > .clean.$$
-#!/bin/sh
+#!/bin/bash
 	
 rm -f *.ko
 rm -f tmp/*.*o
@@ -7277,7 +7297,7 @@ KERNEL_UNAME=`uname -r`
 PKG_NAME=wanpipe
 DISTR_NAME="WANPIPE"
 PROD=wanrouter
-PROD_VER=3.5.23
+PROD_VER=3.5.24
 PROD_HOME=`pwd`
 META_CONF=$PROD_HOME/$PROD.rc
 WAN_INTR_DIR=$PROD_HOME/interfaces
@@ -7836,6 +7856,31 @@ if [ "$PKG_NAME" != "wanpipe-lite" ]; then
 				exit 1;
 			fi
 			;;
+
+        --wanpipe_dev_alloc_cnt*)
+            WANPIPE_DEV_ALLOC_CNT="";
+            WANPIPE_DEV_ALLOC_CNT=`echo $arg | cut -d'=' -f2`;
+
+            echo "WANPIPE_DEV_ALLOC_CNT = $WANPIPE_DEV_ALLOC_CNT"
+            rc=0;
+            if [ "$WANPIPE_DEV_ALLOC_CNT" = "" ]; then
+                rc=1;
+            else
+                if [ $WANPIPE_DEV_ALLOC_CNT -ge 1 ] && [ $WANPIPE_DEV_ALLOC_CNT -le 128 ]; then
+                    rc=0;
+                else
+                    rc=1
+                fi
+            fi
+
+
+            if [ $rc -eq 1 ]; then
+                echo "Error: Invalid WANPIPE_DEV_ALLOC_CNT value: Must be number 1 to 128";
+                exit 1;
+            fi
+            PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DWANPIPE_DEVICE_ALLOC_CNT=$WANPIPE_DEV_ALLOC_CNT "
+            ;;
+
 		--split_rpms*)
 			SPLIT_RPMS="YES";
 			;;
