wanpipe-3.3.11.tgz

diff --git a/Setup b/Setup
--- a/Setup
+++ b/Setup
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash -p
 #
 # Setup		WANPIPE WAN Router Installation/Removal Script.
 #
@@ -9,6 +9,8 @@
 #		as published by the Free Software Foundation; either version
 #		2 of the License, or (at your option) any later version.
 # ----------------------------------------------------------------------------
+# Jul 30, 2008  Jignesh Patel 	Added check for sctp utlity
+# May 30, 2008  Jignesh Patel   Fixed bootscript installation failure
 # Mar 12, 2008  Konrad Hammel   Updated for Zaptel-1.4.9 (kernel sub-dir)
 # Jan 24, 2008  Jignesh Patel   Zaptel Patch Update for 1.4.x 
 # Nov 13, 2007  Konrad Hammel   Minor Updates for aesthetics and usability
@@ -429,7 +431,7 @@ and configuration/debug utilities have been compiled and installed.
 	1) Proceed to configure the WANPIPE drivers:
 		Asterisk/Zaptel: /usr/sbin/wancfg_zaptel
 		TDM API        : /usr/sbin/wancfg_tdmapi
-		SMG SS7        : /usr/sbin/wancfg_smg
+		SMG SS7/BRI    : /usr/sbin/wancfg_smg
 		WAN Routing/API: /usr/sbin/wancfg
 	2) Use the /usr/sbin/wanrouter startup scrip to start and stop
 	   the router. (eg: wanrouter start)
@@ -3007,10 +3009,12 @@ if [ -z $NONINTERACTIVE ]; then
 		enable_protocols "AFT_TE1"
 
 	elif [ "$response"  -eq 6 ]; then
+		check_sctp_utility
                 enable_protocols "AFT_TE1"
                 SSMG_BRI=YES
 
 	elif [ "$response"  -eq 7 ]; then
+		check_sctp_utility
                 enable_protocols "AFT_TE1"
 		enable_protocols "TDM"
                 SSMG_BRI=YES
@@ -3452,19 +3456,36 @@ CFLAGS="$CC -Wp,-MD,.wanpipe.o.d -nostdinc -iwithprefix include -D__LINUX__ -Dli
                                   -e s/ppc.*/powerpc/ -e s/mips.*/mips/ )
 
 
-			#New way of checking REGPARM because its enabled
-			#by default on 2.6.20 kernel and up
+ 			#New way of checking REGPARM because its enabled
+                        #by default on 2.6.20 kernel and up
 			if [ $SUBARCH != "" ]; then
-				eval "grep \"CFLAGS.*=.*-pipe.*regparm\" $SOURCEDIR/arch/$SUBARCH/Makefile" > /dev/null 2> /dev/null
-				if [ $? -eq 0 ]; then
-					echo -e "Enabled.\n"
-		                        REGPARM_OPT=".regparm"
-				else
-					 echo -e "Disabled.\n"
-				fi
-			else
-				 echo -e "Disabled.\n"
-			fi
+                                if [ -f $SOURCEDIR/arch/$SUBARCH/Makefile ]; then
+                                        eval "grep \"CFLAGS.*=.*regparm\" $SOURCEDIR/arch/$SUBARCH/Makefile*" > /dev/null 2> /dev/null
+                                        res=$?
+                                elif [ -d $SOURCEDIR/arch/x86 ]; then
+                                        eval "grep \"CFLAGS.*=*regparm\" $SOURCEDIR/arch/x86/Makefile*" > /dev/null 2> /dev/null
+                                        res=$?
+                                else
+                                        echo
+                                        echo "Warning: Failed to determine regparm from Makefile defaulting to YES!"
+                                        echo
+                                        res=0
+                                fi
+                                if [ $res -eq 0 ]; then
+
+                                        echo -e "Enabled.\n"
+                                        REGPARM_OPT=".regparm"
+                                else
+                                        echo -e "Disabled.\n"
+                                fi
+                        else
+                                echo
+                                echo "Warning: Failed to determine ARCH: regparm defaulting to YES!"
+                                echo
+                                REGPARM_OPT=".regparm"
+                                echo -e "Enabled.\n"
+                        fi
+
 		fi
 
 		
@@ -5257,6 +5278,20 @@ function tdmv_apply_zaptel_chunk_patch () {
 		fi
 	fi
 
+        # for zaptel-1.2.26 or later
+        if [ -f Kbuild ]; then
+                eval "cat Kbuild | sed 's/^obj-m.*+=.*wct4xx.*//g'>$TEMP 2>/dev/null "
+                if [ $? -ne 0 ]; then
+                         echo "   Failed to remove wct4xxp from Kbuild"
+                         exit 1
+
+                else
+                        eval "\mv -f $TEMP Kbuild"
+                        echo "   wct4xxp module removed from Kbuild successfully"
+                        zaptel_modified=1
+                fi
+        fi
+
         cd $lhome
         return 0;
 }
@@ -5944,7 +5979,7 @@ ENDOFTEXT
 	if [ $? -eq 0 ]; then
 		if [ $XMTP2_PROT != YES ]; then
 		echo "Enabling the SS7 XMTP2 Protocol"
-		PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DCONFIG_PRODUCT_WANPIPE_XMTP2 "
+		PROTOCOL_DEFINES="$PROTOCOL_DEFINES -DCONFIG_PRODUCT_WANPIPE_XMTP2 -DAFT_XMTP2_API_SUPPORT "
 		fi
 		PROT_MATCH=YES	
 		XMTP2_PROT=YES
@@ -6465,6 +6500,25 @@ function compile_aft_firmware_util()
         cd $lhome
 }
 
+function check_sctp_utility ()
+{
+	clearscr
+	echo -n "Checking for SCTP Utilities...."
+	if [ ! -e  /usr/include/netinet/sctp.h ] && [ ! -e /usr/include/sctp.h ]; then
+		echo "Failed!"
+		echo "Missing lksctp-tools-devel" >> $CMP_LOG
+                echo "Error: lksctp-tools-devel package missing"
+		echo "Install lksctp-tools-devel package (e.g yum install lksctp-tools-devel)"
+		echo "  "
+		exit 1;
+		
+	else 
+		echo "OK."
+	fi
+
+}
+
+
 function usage()
 {
 	if [ "$PKG_NAME" != "wanpipe-lite" ]; then
@@ -6568,6 +6622,7 @@ or
 		      
 		      TDM    : Hardware TDM VOICE support to Asterisk PBX
 		      
+		      BRI    : Sangoma BRI + Media Gateway Support
 		      
 
 ENDOFTEXT
@@ -6601,7 +6656,7 @@ KERNEL_UNAME=`uname -r`
 PKG_NAME=wanpipe
 DISTR_NAME="WANPIPE"
 PROD=wanrouter
-PROD_VER=3.3.10
+PROD_VER=3.3.11
 PROD_HOME=`pwd`
 META_CONF=$PROD_HOME/$PROD.rc
 WAN_INTR_DIR=$PROD_HOME/interfaces
@@ -7441,14 +7496,15 @@ prepare	|| exit 1
 apply_patches || exit 1
 compile_drivers  || exit 1
 
-if [ $zaptel_auto_install != "YES" ]; then
-install_init || exit 1
-fi
-
 install_config || exit 1
 
 compile_src || exit 1
 install_all 
+
+if [ $zaptel_auto_install != "YES" ]; then
+install_init || exit 1
+fi
+
 install_ssmg
 install_ssmg_bri
 clean_up 
diff --git a/ssmg/sangoma_bri/smg_ctrl b/ssmg/sangoma_bri/smg_ctrl
--- a/ssmg/sangoma_bri/smg_ctrl
+++ b/ssmg/sangoma_bri/smg_ctrl
@@ -2,6 +2,19 @@
 cmd=$1;
 cnt=0;
 max_retry=5;
+use_syslog=1;
+args=' ';
+
+NICE="nice -n -5"
+BRI_NICE="nice -n -10"
+
+while [ ! -z "$2" ]; 
+do
+	args=$args"$2 "
+	shift
+done
+
+
 function stop_all()
 {
 
@@ -103,6 +116,26 @@ function stop_sangoma_mgd()
 
 }
 
+
+function start_test()
+{
+	echo " "
+	echo "Testing configuration files..."
+	if [ $use_syslog -eq 1 ]; then
+		eval "$BRI_NICE sangoma_brid -t"
+	else 
+		eval "$BRI_NICE sangoma_brid -t -log"
+	fi
+
+	if [ $? -eq 0 ]; then
+		echo "OK"
+	else 
+		echo "Failed"
+	fi
+	
+}
+
+
 function start_all()
 {
 
@@ -128,7 +161,11 @@ function start_all()
 	fi
 
 	echo -n "Starting sangoma_brid..."
-	eval "sangoma_brid >/dev/null 2>/dev/null &" 
+	if [ $use_syslog -eq 1 ]; then
+		eval "$BRI_NICE sangoma_brid  >/dev/null 2>/dev/null &" 
+	else 
+		eval "$BRI_NICE sangoma_brid -log >/dev/null 2>/dev/null &" 
+	fi
 	if [ $?	-eq 0 ]; then
 		echo "OK"
 	else 
@@ -136,7 +173,7 @@ function start_all()
 		echo "Failed to start sangoma_brid, check /var/log/sangoma_mgd.log for errors"
 		exit 1;
 	fi
-	sleep 2 
+	sleep 10
 	if [ ! $(pidof sangoma_brid) ]; then
 		echo "sangoma_brid failed to start"
 		echo "check /var/log/sangoma_mgd.log for errors"
@@ -144,7 +181,7 @@ function start_all()
 	fi
 
 	echo -n "Starting sangoma_mgd..."
-	eval "sangoma_mgd -bg >/dev/null 2>/dev/null" 
+	eval "$NICE sangoma_mgd -bg >/dev/null 2>/dev/null" 
 	if [ $? -eq 0 ]; then
 		echo "OK"
 	else 
@@ -161,22 +198,32 @@ function start_all()
 	fi
 
 	echo "Sangoma SMG running.."
-	echo "log file: /var/log/sangoma_mgd.log"
+	if [ $use_syslog -eq 1 ]; then
+		echo "log file: /var/log/sangoma_mgd.log"
+	else
+		echo "log file: /var/log/sangoma_mgd/sangoma_mgd.log"
+	fi
 	echo " "
 }
 
 function usage()
 {
 	echo " "
-	echo "Usage: smg_ctrl <options>"
-	echo "	options:"
+	echo "Usage: smg_ctrl <command> [options]"
+	echo "command:"
 	echo " "
 	echo "start	:start sangoma_brid and sangoma media gateway"
 	echo "stop 	:stop sangoma_brid and sangoma media gateway"
 	echo "restart	:restart sangoma_brid and sangoma media gateway"
+	echo "test	:test sangoma_brid configuration files without"
+	echo "		 applying changes"
+	echo " "
+	echo "options:"
+	echo "nosyslog  :does not use syslog to log data"
 	echo " "
 
 }
+
 function check_running ()
 {
 	if [ $(pidof sangoma_brid) ]; then
@@ -257,6 +304,22 @@ function show_spans()
 	fi
 }
 
+function parse_args()
+{
+	for arg in $args
+	do
+		case $arg in 
+			nosyslog)
+				use_syslog=0;
+				;;
+		esac
+
+	done	
+}
+
+parse_args
+
+
 if [ "$cmd" = "start" ]; then
 	check_running
 	start_all
@@ -275,6 +338,8 @@ elif [ "$cmd" = "show_spans" ]; then
 	show_spans
 elif [ "$cmd" = "show_calls" ]; then
 	show_calls
+elif [ "$cmd" = "test" ]; then
+	start_test
 else 
 	usage
 fi
diff --git a/ssmg/sangoma_mgd.trunk/install b/ssmg/sangoma_mgd.trunk/install
--- a/ssmg/sangoma_mgd.trunk/install
+++ b/ssmg/sangoma_mgd.trunk/install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # ----------------------------------------------------------------------------
 # Prompt user for input.
@@ -46,6 +46,8 @@ pbxdir=/usr/src/asterisk
 pbxd="asterisk"
 cfgdir="/etc/asterisk"
 mysyslog=" "
+smg_installed=0
+chan_woomera_installed=0
 
 
 
@@ -59,10 +61,10 @@ do
 		shift
                 pbxdir=$1
                 if [ "$pbxdir" = "" ]; then
-                        echo "Error: Invalid $pbxd dir: $pbxdir!";
+                        echo "Error: Invalid -pbxdir input argument: $pbxdir!";
                         exit 1
                 elif [ ! -d $pbxdir ]; then
-                        echo "Error: $pbxd dir does not exist: $pbxdir!";
+                        echo "Error: directory does not exist: $pbxdir!";
                         exit 1
                 fi
 
@@ -111,7 +113,6 @@ fi
 if [ $force = "force" ]; then
 	echo "Stopping SMG..."
 	eval "sangoma_mgd -term"
-        kill -TERM $(pidof asterisk);
 	echo "OK."
 	echo
 else 
@@ -128,23 +129,6 @@ else
 			exit 1
 		fi
 	fi
-	if [ -f /var/run/asterisk.pid ]; then
-		echo "Warning: asterisk is running"
-		getyn "Would you like to stop asterisk?"
-		if [ $? -ne 0 ]; then
-			exit 1
-		fi
-		eval "asterisk -rx \"stop now\" >/dev/null 2>/dev/null"
-		sleep 2
-		if [ -f /var/run/asterisk.pid ]; then
-       			kill -TERM $(pidof asterisk);
-			sleep 2
-			if [ -f /var/run/asterisk.pid ]; then
-				echo "Failed to stop asterisk"
-				exit 1
-			fi
-		fi
-	fi
 fi
 
 echo
@@ -156,8 +140,15 @@ elif [ -e /etc/rsyslog.conf ] ; then
         echo " found /etc/rsyslog.conf "
         mysyslog='rsyslog'
 else
-               echo " Warning : Syslog not found "
-               mysyslog=" "
+        echo " Warning : Syslog not found "
+	echo " This install script is optimized for RedHat/Centos/Fedora Distributions"
+	getyn "Would you like to proceed?"
+	if [ $? -ne 0 ]; then
+		exit 1
+	fi	
+
+        mysyslog=" "
+	
 fi
 
 
@@ -231,7 +222,11 @@ echo "OK."
 echo
 echo "Checking for SCTP Utilities...."
 if [ ! -e  /usr/include/netinet/sctp.h ] && [ ! -e /usr/include/sctp.h ]; then
+	echo
 	echo "Error: lksctp-tools-devel package missing"
+	echo "Please install sctp using a package manager"
+	echo "eg: yum install ksctp-tools-devel"
+	echo
 	exit 1
 fi 
 echo "OK."
@@ -255,7 +250,7 @@ echo
 
 echo "Compiling Sangoma MGD ..."
 eval "make clean 2> /dev/null > /dev/null"
-if [ $noss7 == 'true' ]; then
+if [ $noss7 = "true" ]; then
         eval "make NO_SS7=YES" 
 else
         eval "make" 
@@ -265,12 +260,25 @@ if [ $? -ne 0 ]; then
 	exit 1;
 fi
 
-if [ $noss7 == 'true' ]; then
-	make INSTALLPREFIX=$rootdir NO_SS7=YES install
+if [ $noss7 = "true" ]; then
+	#This case is currently used for bri
+	eval "make INSTALLPREFIX=$rootdir NO_SS7=YES install"
 else
-	make INSTALLPREFIX=$rootdir install
+	eval "make INSTALLPREFIX=$rootdir install"
 fi
-echo "Ok."
+
+if [ $? -ne 0 ]; then
+	echo
+	echo " SMG Installation Failed"
+	echo 
+	echo " Please contact Sangoma Support"
+	echo " http://wiki.sangoma.com"
+	echo
+	exit 1;
+else
+	echo "Ok."
+	smg_installed=1;
+fi
 
 if [ -d chan_woomera.trunk ]; then
 
@@ -281,41 +289,68 @@ if [ -d chan_woomera.trunk ]; then
 	if [ ! -e $pbxdir ]; then
 		echo
 		echo "Error: $pbxdir directory does not exist!"
-		echo "       Please create symlink /usr/src/asterisk and"
-		echo "       point to existing asterisk source!"
-		echo "       Then re run ./install.sh "
+		echo "       Please provide the path to Asterik or CallWeaver source."
+		echo "       Then re-run eg: ./install -pbxdir /usr/src/asterisk "
 		echo
-		exit 1
+	else
+		eval "make clean 2> /dev/null > /dev/null"
+		eval "make PBXDIR=$pbxdir"
+		if [ $? -ne 0 ]; then
+			exit 1;
+		fi
+		make INSTALLPREFIX=$rootdir install
+		if [ $? -ne 0 ]; then
+			echo
+			echo "Error: Failed to compile chan_woomera into PBX source!"
+			echo
+			exit 1;
+		fi
+		echo "Ok."
+		chan_woomera_installed=1;
 	fi
-
-	eval "make clean 2> /dev/null > /dev/null"
-	eval "make PBXDIR=$pbxdir"
-	if [ $? -ne 0 ]; then
-		exit 1;
-	fi
-
-	make INSTALLPREFIX=$rootdir install
-	echo "Ok."
 
 else
 	echo "Warning: chan_woomera directory does not exist!"
 	exit 1
 fi
 
+if [ $smg_installed -eq 1 ]; then
+	echo "---------------------------------"
+	echo
+	echo " SMG Install Done"
+	echo
+	echo "--> Config: /etc/sangoma_mgd.conf"
+	echo "--> Start:  sangoma_mgd -bg"
+	echo
+else
+	echo "---------------------------------"
+	echo
+	echo " SMG Installation Failed"
+	echo 
+	echo " Please contact Sangoma Support"
+	echo " http://wiki.sangoma.com"
+	echo
+fi
 
-echo "---------------------------------"
-echo
-echo " SMG Install Done"
-echo
-echo "--> Config: /etc/sangoma_mgd.conf"
-echo "--> Start:  sangoma_mgd -bg"
-echo
-echo " Chan Woomera Install Done"
-echo 
-echo "--> Config: $cfgdir/woomera.conf"
-echo "--> Start: start $pbxd (part of $pbxd)"
-echo
-echo "---------------------------------"
+if [ $chan_woomera_installed -eq 1 ]; then
+	echo
+	echo " Chan Woomera Install Done"
+	echo 
+	echo "--> Config: $cfgdir/woomera.conf"
+	echo "--> Start: start $pbxd (part of $pbxd)"
+	echo
+	echo "---------------------------------"
+else
+	echo
+	echo " Chan Woomera Installatin Failed"
+	echo 
+	echo " If you are running Asteirsk/CallWeaver on another system"
+	echo " ignore this message. Otherwise please contact"
+	echo " Sangoma Support."
+	echo " http://wiki.sangoma.com"
+	echo
+	echo "---------------------------------"
+fi
 
 exit 0
 
