wanpipe-3.2.6.tgz

diff --git a/Setup b/Setup
--- a/Setup
+++ b/Setup
@@ -9,6 +9,7 @@
 #		as published by the Free Software Foundation; either version
 #		2 of the License, or (at your option) any later version.
 # ----------------------------------------------------------------------------
+# May 30, 2008  Jignesh Patel   Fixed bootscript installation failure 
 # Oct 26, 2007  Konrad Hammel   Updated minor start script bug
 # Nov 27, 2005  David Rokhvarg 	Added Echo Debugging option
 # Mar 18, 2002  Nenad Corbic	Added BSCSTRM protocol
@@ -3320,20 +3321,35 @@ CFLAGS="$CC -Wp,-MD,.wanpipe.o.d -nostdinc -iwithprefix include -D__LINUX__ -Dli
                                   -e s/s390x/s390/ -e s/parisc64/parisc/ \
                                   -e s/ppc.*/powerpc/ -e s/mips.*/mips/ )
 
-
 			#New way of checking REGPARM because its enabled
-			#by default on 2.6.20 kernel and up
-			if [ $SUBARCH != "" ]; then
-				eval "grep \"CFLAGS.*=.*-pipe.*regparm\" $SOURCEDIR/arch/$SUBARCH/Makefile" > /dev/null 2> /dev/null
-				if [ $? -eq 0 ]; then
-					echo -e "Enabled.\n"
-		                        REGPARM_OPT=".regparm"
-				else
-					 echo -e "Disabled.\n"
-				fi
-			else
-				 echo -e "Disabled.\n"
-			fi
+                        #by default on 2.6.20 kernel and up
+                        if [ $SUBARCH != "" ]; then
+				if [ -f $SOURCEDIR/arch/$SUBARCH/Makefile ]; then
+                                	eval "grep \"CFLAGS.*=.*regparm\" $SOURCEDIR/arch/$SUBARCH/Makefile*" > /dev/null 2> /dev/null
+					res=$?
+                                elif [ -d $SOURCEDIR/arch/x86 ]; then
+                                	eval "grep \"CFLAGS.*=*regparm\" $SOURCEDIR/arch/x86/Makefile*" > /dev/null 2> /dev/null
+					res=$?
+                                else
+                                        echo
+                                        echo "Warning: Failed to determine regparm from Makefile defaulting to YES!"
+                                        echo
+                                        res=0
+                                fi
+                                if [ $res -eq 0 ]; then
+
+                                        echo -e "Enabled.\n"
+                                        REGPARM_OPT=".regparm"
+                                else
+                                        echo -e "Disabled.\n"
+                                fi
+                        else
+                                echo
+                                echo "Warning: Failed to determine ARCH: regparm defaulting to YES!"
+                                echo
+                                REGPARM_OPT=".regparm"
+                                echo -e "Enabled.\n"
+                        fi
 		fi
 
 		
@@ -6341,7 +6357,7 @@ KERNEL_UNAME=`uname -r`
 PKG_NAME=wanpipe
 DISTR_NAME="WANPIPE"
 PROD=wanrouter
-PROD_VER=3.2.5
+PROD_VER=3.2.6
 PROD_HOME=`pwd`
 WAN_CONF_DIR=/etc/wanpipe
 META_CONF=$PROD_HOME/$PROD.rc      
@@ -7141,10 +7157,10 @@ welcome || exit 0
 prepare	|| exit 1
 apply_patches || exit 1
 compile_drivers  || exit 1
-install_init || exit 1
 install_config || exit 1   
 compile_src || exit 1
 install_all 
+install_init || exit 1
 install_ssmg
 clean_up 
 goodbye
diff --git a/samples/wanrouter b/samples/wanrouter
--- a/samples/wanrouter
+++ b/samples/wanrouter
@@ -1752,6 +1752,78 @@ function wanrouter_if_debug()
 	fi
 }
 
+
+
+pci_parity_ctrl ()
+{
+	local parity_cmd;
+	local pdev;
+	local IDS;
+	local verbosity=${2:-1}
+
+	if [ $OSYSTEM != "Linux" ]; then
+		echo "Error: PCI Parity Ctrl only available on Linux"
+		echo
+		return
+	fi
+
+	IDS=`lspci | cut -d' ' -f1`
+
+	if [ -z $1 ]; then
+		echo "Displaying System PCI Parity Configuration";
+		echo "=========================================="
+		echo
+		lspci -vvv | grep Parity
+		echo
+		echo "=========================================="
+		return
+	fi
+	
+	parity_cmd=${1:-"off"}
+
+	if [ $parity_cmd != "on" ]; then
+		parity_cmd="off";
+	fi
+
+	eval "type setpci 2> /dev/null > /dev/null"
+	if [ $? -ne 0 ]; then
+		echo "Parity Set Error: setpci utility not found!"
+		return
+	fi
+
+	if [ $verbosity -gt 0 ]; then
+		echo "Setting PCI Parity to $parity_cmd";
+	fi
+
+	for pdev in $IDS
+	do
+		if [ "$parity_cmd" = "on" ]; then
+			eval "setpci -s $pdev 3e.b=0x7"
+		else
+			eval "setpci -s $pdev 3e.b=0x4"
+		fi
+
+	done
+
+	return
+}
+
+wanrouter_pre_start()
+{
+	
+	if [ "$WAN_PCI_PARITY" = "OFF" ]; then
+		echo "Wanrouter: Disabling PCI Parity on Start!" >> $WAN_LOG;
+		pci_parity_ctrl "off" 0
+	elif [ "$WAN_PCI_PARITY" = "ON" ]; then
+		echo "Wanrouter: Enabling PCI Parity on Start!" >> $WAN_LOG;
+		pci_parity_ctrl "on" 0
+	fi
+}
+
+
+
+
+
 function wanrouter_debug ()
 {
 	local err=0
@@ -2106,7 +2178,7 @@ WANPIPE_IS_RUNNING=/var/run/wanpipe_is_running
 RUGGEDCOM=No
 
 if [ $OSYSTEM = "Linux" ]; then
-	ROUTER_VERSION=3.2.5
+	ROUTER_VERSION=3.2.6
 	IFCONFIG_LIST=ifconfig
 	MODULE_STAT=lsmod
 	WAN_DRIVERS="wanpipe"
@@ -2375,6 +2447,8 @@ case "$1" in
 				cleanup 2
 			fi
 
+			wanrouter_pre_start
+
 			config_devices $WAN_DEVICES
 
 			config_interfaces $WAN_DEVICES
@@ -2410,6 +2484,8 @@ case "$1" in
 			if [ $ft1_or_wanpipe -gt 0 ]; then
 				dev="wanpipe$ft1_or_wanpipe"
 			fi 
+
+			wanrouter_pre_start
 
 			config_devices $dev
 			if [ $? -ne 0 ]; then
@@ -2456,6 +2532,8 @@ case "$1" in
 				echo -e "\nInterface $if_name is already up!\n"
 				cleanup 1
 			fi
+
+			wanrouter_pre_start
 		
 			echo "Configuring interface: $if_name"
 
@@ -2850,6 +2928,11 @@ case "$1" in
 		fi
 		cleanup 0;
 		;;
+
+	parity)
+		pci_parity_ctrl $2
+		;;
+
 
 	wanrc)
 		
